# ~/urdf_ws/src/my_robot_moveit_config/config/joint_limits.yaml
move_group:
  ros__parameters:
    joint_limits:
      J1:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0
      J2:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0
      J3:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0
      J4:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0
      J5:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0
      J6:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0
      gripper_left_joint:
        has_velocity_limits: true
        max_velocity: 0.05
        has_acceleration_limits: true
        max_acceleration: 0.5
