controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      ros__parameters:
        joints:
          - J1
          - J2
          - J3
          - J4
          - J5
          - J6
          - gripper_left_joint
        interfaces:
          - position
          - velocity
    robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController

robot_controller:
  ros__parameters:
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
      - gripper_left_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
